name: minecraft-status

services:
  web:
    image: minecraft-status:dev
    container_name: minecraft-status
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
